# Generated by Django 5.1 on 2024-08-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loginify', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetails',
            options={'ordering': ('username',), 'verbose_name_plural': 'UserDetails'},
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='password',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='username',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
