# Generated by Django 5.1 on 2024-08-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loginify', '0002_alter_userdetails_options_remove_userdetails_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
